### ISSUE TITLE
Reading GMSA passwords

### ISSUE THREAD

**Issue by jsdhasfedssad** [cube0x0/KrbRelay#3]
I am trying to read the password of a GMSA account. In this case the password is either not found or I am unable to read it since I cannot connect to LDAP over TLS. I can read the password just fine using for example the tool BloodyAD and the same domain admin account (session 1) I am using here.

If I connect without TLS the connection is successful but the password is not found. That is how I understand the output anyway but maybe that is not correct?

![gmsa_no_ssl](https://user-images.githubusercontent.com/97032878/154097063-5ce9a48b-a42f-426e-8c33-e373b9aed455.png)

If I instead try to connect using TLS, as shown in your examples, the connections fails.

![gmsa_with_ssl](https://user-images.githubusercontent.com/97032878/154097191-24cc1676-daa1-428b-bbe4-7cdbc49929bd.png)

I am aware that in order to use TLS, certificates must be configured. To show that that is the case I use nmap on port 389 and 636.

![gmsa_certs](https://user-images.githubusercontent.com/97032878/154097521-3ee6f641-ac71-40ad-a65f-489a095c1560.png)

I am also aware that LDAP signing and/or chanel binding can cause issues so I show that those are not enabled using the tool LdapRelayScan.

![gmsa_check](https://user-images.githubusercontent.com/97032878/154097818-fc15f40a-12c9-4548-a7aa-76ddc3653642.png)

What is the problem here?

**Comment by cube0x0** [comment]
gMSA can only be read from ssl
relaying to LDAPS works if the default certificate on the DC has not been replaced with a self signed cert. Working on a fix

**Comment by jsdhasfedssad** [comment]
I tested your fix but I get an error. Please fix the fix :) BTW, I use ADCS in my lab which is where the certificates are coming from. This is common out there so trusting self signed certificates is vital.

![gmsa_error1](https://user-images.githubusercontent.com/97032878/154224233-ef44e99b-8ead-456d-8096-24906b9ba0fc.png)
